name: create_network_infra
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/create_network_infra.yml'
      - 'network_infra/modules/**'
      - 'network_infra/**.tf'
jobs:
  terraform_plan:
    defaults:
      run:
        working-directory: ./orchestration
    runs-on: ubuntu-latest
    env:
      STAGE_FILE: "docker-compose.network-infra.yml"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      run: make run_plan

  terraform_apply:
    defaults:
      run:
        working-directory: ./orchestration
    environment:
      name: approval
    needs: terraform_plan
    runs-on: ubuntu-latest
    env:
      STAGE_FILE: "docker-compose.network-infra.yml"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      run: make run_plan
    - name: Terraform_Apply
      run: make run_apply  
